In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
val_path = "data/global_split/reviews_Beauty_5/validation.csv"
train_path = "data/global_split/reviews_Beauty_5/train.csv"
test_path = "data/global_split/reviews_Beauty_5/test.csv"
val = pd.read_csv(val_path)
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [18]:
(train.groupby(by="user_id").count()["item_id"] < 3).sum()

np.int64(1646)

In [ ]:
df = (train.groupby(by="user_id").count()["item_id"] < 3)
bad_users = df[df].index

Index([   11,    16,    18,    39,    61,    73,    78,   101,   109,   116,
       ...
       22153, 22178, 22205, 22246, 22265, 22275, 22276, 22289, 22291, 22318],
      dtype='int64', name='user_id', length=1646)

In [ ]:
validation = train.groupby(by="user_id").last().reset_index()

       user_id  item_id  rating   timestamp
0            1        1       1  1391040000
1            3      243       1  1393545600
2            4        1       1  1386460800
3            5    11444       1  1384992000
4            6     5664       1  1392422400
...        ...      ...     ...         ...
20218    22333    11810       1  1390435200
20219    22334    11941       1  1392768000
20220    22335    11941       1  1393632000
20221    22336    11941       1  1394064000
20222    22340    11941       1  1393632000

[20223 rows x 4 columns]

In [7]:
train

        user_id  item_id  rating   timestamp
0           225      104       1  1023840000
1           225      101       1  1024185600
2           225      102       1  1024185600
3          1115      152       1  1036627200
4           225       23       1  1052611200
...         ...      ...     ...         ...
138162    13627    11768       1  1394150400
138163    15343    11768       1  1394150400
138164     3541    11770       1  1394150400
138165     2670    11774       1  1394150400
138166     1085    11776       1  1394150400

[138167 rows x 4 columns]

In [8]:
len(set(test.user_id).difference(set(train.user_id)))

2140

In [14]:
df

       user_id  item_id  rating   timestamp
0            1     5406       1  1391040000
1            3    11204       1  1393804800
2            4     7849       1  1386460800
3            5    11390       1  1388966400
4            6     7595       1  1392422400
...        ...      ...     ...         ...
20218    22333    11893       1  1392681600
20219    22334    11942       1  1392768000
20220    22335    11966       1  1393632000
20221    22336    11966       1  1394064000
20222    22340    11942       1  1393632000

[20223 rows x 4 columns]

In [18]:
data_path = "data/global_split/reviews_Beauty_5/validation.csv"
all_data_path = "data/reviews_Beauty_5.csv"
df = pd.read_csv(data_path)
all_data = pd.read_csv(all_data_path)
max_sequence_length = 10
index = []
for _, (val_user_id, val_item_id, val_rating, val_timestamp) in tqdm(
    df.iterrows(), total=len(df), desc="Validation ds creation"
):
    user_info = all_data[all_data.user_id == val_user_id]
    previous_user_info = user_info[user_info.timestamp <= val_timestamp].copy()
    # to make out item last
    previous_user_info.loc[previous_user_info.user_id == val_user_id, "timestamp"] += 1
    previous_user_info = previous_user_info.reset_index().sort_values(
        by=["timestamp", "index"]
    )
    previous_user_items = previous_user_info.item_id.tolist()
    assert previous_user_items[-1] == val_item_id
    item_sequence = previous_user_items[-max_sequence_length :]
    index.append(
        {
            "user.ids": [val_user_id],
            "user.length": 1,
            "item.ids": item_sequence,
            "item.length": len(item_sequence),
        }
    )

Validation ds creation: 100%|██████████| 20223/20223 [00:12<00:00, 1622.51it/s]

In [19]:
index

[{'user.ids': [1],
  'user.length': 1,
  'item.ids': [6846, 7873, 4585, 1, 5406],
  'item.length': 5},
 {'user.ids': [3],
  'user.length': 1,
  'item.ids': [1, 6050, 7977, 5252, 4211, 243, 11204],
  'item.length': 7},
 {'user.ids': [4],
  'user.length': 1,
  'item.ids': [5522, 439, 5161, 11140, 1, 7849],
  'item.length': 6},
 {'user.ids': [5],
  'user.length': 1,
  'item.ids': [1, 10470, 10064, 9403, 10362, 4758, 6500, 11444, 11390],
  'item.length': 9},
 {'user.ids': [6],
  'user.length': 1,
  'item.ids': [8816, 4595, 9917, 6046, 9597, 8819, 6431, 9562, 5664, 7595],
  'item.length': 10},
 {'user.ids': [7],
  'user.length': 1,
  'item.ids': [8499, 8778, 1796, 5987, 6059, 10038, 1],
  'item.length': 7},
 {'user.ids': [8],
  'user.length': 1,
  'item.ids': [8997, 4554, 6928, 1, 2367],
  'item.length': 5},
 {'user.ids': [9],
  'user.length': 1,
  'item.ids': [3697, 5488, 11243, 11288, 10357, 3894, 4352, 9557, 3362, 3788],
  'item.length': 10},
 {'user.ids': [10],
  'user.length': 1,
  'item.ids': [1928, 2171, 2228, 2, 2028],
  'item.length': 5},
 {'user.ids': [11],
  'user.length': 1,
  'item.ids': [1190, 5074],
  'item.length': 2},
 {'user.ids': [12],
  'user.length': 1,
  'item.ids': [4211, 3275, 6325, 9046, 7591, 2, 8643, 10609],
  'item.length': 8},
 {'user.ids': [13],
  'user.length': 1,
  'item.ids': [6322, 5528, 7437, 10874, 2],
  'item.length': 5},
 {'user.ids': [14],
  'user.length': 1,
  'item.ids': [2, 138, 2937, 5128, 8517, 1307, 8327, 11119],
  'item.length': 8},
 {'user.ids': [15],
  'user.length': 1,
  'item.ids': [11518, 8579, 11256, 2, 1305, 2047, 11788],
  'item.length': 7},
 {'user.ids': [16],
  'user.length': 1,
  'item.ids': [6276, 9654],
  'item.length': 2},
 {'user.ids': [17],
  'user.length': 1,
  'item.ids': [6534, 8958, 2, 2421, 2449],
  'item.length': 5},
 {'user.ids': [18],
  'user.length': 1,
  'item.ids': [11111, 2],
  'item.length': 2},
 {'user.ids': [19],
  'user.length': 1,
  'item.ids': [5244, 8815, 2, 10207],
  'item.length': 4},
 {'user.ids': [20],
  'user.length': 1,
  'item.ids': [390, 9165, 3208, 6231, 8966, 9272, 6161, 5040, 7840, 7857],
  'item.length': 10},
 {'user.ids': [21],
  'user.length': 1,
  'item.ids': [2837, 7830, 3, 816, 1426, 3538, 6869],
  'item.length': 7},
 {'user.ids': [22],
  'user.length': 1,
  'item.ids': [6158, 5379, 9600, 298, 10781, 11070, 8543, 1354, 71, 2941],
  'item.length': 10},
 {'user.ids': [23],
  'user.length': 1,
  'item.ids': [891, 1950, 1971, 2060, 2544, 2992, 4064, 5259, 5318, 3],
  'item.length': 10},
 {'user.ids': [24],
  'user.length': 1,
  'item.ids': [6304, 7363, 7678, 3, 7907, 8789, 8661, 9673, 10068],
  'item.length': 9},
 {'user.ids': [26],
  'user.length': 1,
  'item.ids': [6649, 1596, 2544, 3537, 5688, 4, 1977, 502, 1071],
  'item.length': 9},
 {'user.ids': [27],
  'user.length': 1,
  'item.ids': [6599,
   9781,
   10632,
   11575,
   10472,
   7849,
   9839,
   10594,
   11004,
   7977],
  'item.length': 10},
 {'user.ids': [28],
  'user.length': 1,
  'item.ids': [1076, 1423, 1477, 6285, 1015, 4588, 4],
  'item.length': 7},
 {'user.ids': [29],
  'user.length': 1,
  'item.ids': [8802, 7469, 10822, 5325, 8087, 3903, 4, 9045],
  'item.length': 8},
 {'user.ids': [30],
  'user.length': 1,
  'item.ids': [921, 730, 6192, 4460, 1854, 1712, 3756, 414, 4],
  'item.length': 9},
 {'user.ids': [31],
  'user.length': 1,
  'item.ids': [5, 3099, 1251, 759, 6778],
  'item.length': 5},
 {'user.ids': [32],
  'user.length': 1,
  'item.ids': [1135,
   10669,
   10689,
   1166,
   10896,
   11734,
   11732,
   7114,
   11772,
   11773],
  'item.length': 10},
 {'user.ids': [33],
  'user.length': 1,
  'item.ids': [3373, 1755, 2315, 2791, 3799, 5113, 388, 3314, 9672, 2668],
  'item.length': 10},
 {'user.ids': [34],
  'user.length': 1,
  'item.ids': [791, 2413, 2452, 801, 1974, 1433, 1363, 2171, 55, 1355],
  'item.length': 10},
 {'user.ids': [35],
  'user.length': 1,
  'item.ids': [7436, 11474, 5, 265, 3272, 5416, 6037, 10089, 10136, 10381],
  'item.length': 10},
 {'user.ids': [36],
  'user.length': 1,
  'item.ids': [4667, 7037, 9224, 5935, 6693, 6811, 10323, 6169, 6613, 3169],
  'item.length': 10},
 {'user.ids': [37],
  'user.length': 1,
  'item.ids': [6, 999, 1247, 1452, 5273, 6046, 8090],
  'item.length': 7},
 {'user.ids': [39],
  'user.length': 1,
  'item.ids': [464, 4993, 6825],
  'item.length': 3},
 {'user.ids': [40],
  'user.length': 1,
  'item.ids': [8249, 8816, 9081, 85, 5194, 6, 3579, 9603, 9716, 3580],
  'item.length': 10},
 {'user.ids': [41],
  'user.length': 1,
  'item.ids': [4866, 6352, 8042, 6, 611],
  'item.length': 5},
 {'user.ids': [42],
  'user.length': 1,
  'item.ids': [6, 7155, 3498, 2329, 3540, 6547, 921, 4367, 6589, 8662],
  'item.length': 10},
 {'user.ids': [43],
  'user.length': 1,
  'item.ids': [1636, 2319, 2758, 6501, 628, 1138, 1249, 312, 3788, 6],
  'item.length': 10},
 {'user.ids': [44],
  'user.length': 1,
  'item.ids': [4230, 2262, 2310, 4108, 5053, 5903, 8249, 8478, 9329, 10435],
  'item.length': 10},
 {'user.ids': [45],
  'user.length': 1,
  'item.ids': [4899, 2358, 6, 1245, 1609, 1611],
  'item.length': 6},
 {'user.ids': [46],
  'user.length': 1,
  'item.ids': [6, 1024, 840, 8421, 8690],
  'item.length': 5},
 {'user.ids': [47],
  'user.length': 1,
  'item.ids': [2854, 6, 370, 447, 2426, 2830, 2158, 6291],
  'item.length': 8},
 {'user.ids': [48],
  'user.length': 1,
  'item.ids': [3068, 318, 493, 6, 3647, 8062],
  'item.length': 6},
 {'user.ids': [49],
  'user.length': 1,
  'item.ids': [2076, 2420, 6, 4966, 3068, 6584, 7727, 2183, 772, 2972],
  'item.length': 10},
 {'user.ids': [50],
  'user.length': 1,
  'item.ids': [7595, 2599, 5193, 9947, 7791, 6, 6266, 9714, 9061, 3298],
  'item.length': 10},
 {'user.ids': [51],
  'user.length': 1,
  'item.ids': [1318, 4207, 4955, 9215, 5751, 577, 7683, 6],
  'item.length': 8},
 {'user.ids': [52],
  'user.length': 1,
  'item.ids': [4691, 6, 9471, 388, 390, 6683, 7751],
  'item.length': 7},
 {'user.ids': [53],
  'user.length': 1,
  'item.ids': [6, 5314, 5749, 5307, 5382, 6821],
  'item.length': 6},
 {'user.ids': [54],
  'user.length': 1,
  'item.ids': [5926, 6982, 7499, 6, 494, 2764, 6573, 6833, 8772, 10341],
  'item.length': 10},
 {'user.ids': [55],
  'user.length': 1,
  'item.ids': [6, 196, 444, 689, 727, 4768, 8048, 1213],
  'item.length': 8},
 {'user.ids': [57],
  'user.length': 1,
  'item.ids': [6, 1307, 1732, 5803, 6552, 9163, 5973],
  'item.length': 7},
 {'user.ids': [58],
  'user.length': 1,
  'item.ids': [4449, 8252, 2148, 5488, 4868, 7, 5878, 2045, 8300],
  'item.length': 9},
 {'user.ids': [59],
  'user.length': 1,
  'item.ids': [7, 7130, 8518, 8615, 8648, 8386, 8872],
  'item.length': 7},
 {'user.ids': [60],
  'user.length': 1,
  'item.ids': [931, 2335, 7, 1567, 2868, 3216, 8166, 9969],
  'item.length': 8},
 {'user.ids': [61],
  'user.length': 1,
  'item.ids': [7, 4956, 4876],
  'item.length': 3},
 {'user.ids': [62],
  'user.length': 1,
  'item.ids': [5908, 7, 1414, 220, 7074],
  'item.length': 5},
 {'user.ids': [63],
  'user.length': 1,
  'item.ids': [10566,
   10700,
   10698,
   10897,
   10164,
   10691,
   10896,
   10373,
   10374,
   8229],
  'item.length': 10},
 {'user.ids': [64],
  'user.length': 1,
  'item.ids': [7, 2710, 5294, 4205, 3768, 2776, 6613, 2778, 8733],
  'item.length': 9},
 {'user.ids': [65],
  'user.length': 1,
  'item.ids': [4050, 3916, 4675, 8351, 8384, 4647, 4779],
  'item.length': 7},
 {'user.ids': [66],
  'user.length': 1,
  'item.ids': [5385, 3650, 7, 4967],
  'item.length': 4},
 {'user.ids': [67],
  'user.length': 1,
  'item.ids': [3339, 9782, 5410, 9476, 7, 9255],
  'item.length': 6},
 {'user.ids': [68],
  'user.length': 1,
  'item.ids': [4201, 7, 1818, 9816, 1775],
  'item.length': 5},
 {'user.ids': [69],
  'user.length': 1,
  'item.ids': [7, 8227, 8, 2532, 4899],
  'item.length': 5},
 {'user.ids': [70],
  'user.length': 1,
  'item.ids': [9288,
   10689,
   10984,
   8387,
   10896,
   3625,
   5931,
   3311,
   10378,
   11801],
  'item.length': 10},
 {'user.ids': [71],
  'user.length': 1,
  'item.ids': [7, 6727, 917, 8267, 8268],
  'item.length': 5},
 {'user.ids': [73],
  'user.length': 1,
  'item.ids': [7670, 7, 1788],
  'item.length': 3},
 {'user.ids': [74],
  'user.length': 1,
  'item.ids': [11379, 51, 2028, 2648, 2789, 3060, 3298, 4341, 6192, 7],
  'item.length': 10},
 {'user.ids': [76],
  'user.length': 1,
  'item.ids': [7, 2035, 2253, 3046, 8631],
  'item.length': 5},
 {'user.ids': [77],
  'user.length': 1,
  'item.ids': [7314, 7, 6866, 6844, 7910],
  'item.length': 5},
 {'user.ids': [78],
  'user.length': 1,
  'item.ids': [2261, 1089, 2302],
  'item.length': 3},
 {'user.ids': [79],
  'user.length': 1,
  'item.ids': [8727,
   9550,
   3712,
   11647,
   11760,
   11777,
   11804,
   4016,
   11773,
   11778],
  'item.length': 10},
 {'user.ids': [80],
  'user.length': 1,
  'item.ids': [3885, 536, 3811, 4735, 5749, 8300, 9612, 5987, 9144, 10978],
  'item.length': 10},
 {'user.ids': [81],
  'user.length': 1,
  'item.ids': [6770, 6830, 1282, 5718, 159, 8678, 21, 6274, 149, 3222],
  'item.length': 10},
 {'user.ids': [82],
  'user.length': 1,
  'item.ids': [8, 7138, 8969, 7532, 8633, 8824, 2987, 9712, 6880, 3941],
  'item.length': 10},
 {'user.ids': [83],
  'user.length': 1,
  'item.ids': [611, 2493, 3337, 3567, 5465, 5473, 5698, 7594, 8631, 9925],
  'item.length': 10},
 {'user.ids': [84],
  'user.length': 1,
  'item.ids': [4653, 8730, 9585, 5369, 2346, 8, 10302, 3856, 10377, 11144],
  'item.length': 10},
 {'user.ids': [85],
  'user.length': 1,
  'item.ids': [2393, 6589, 2605, 9, 3813, 4085, 6269, 11194, 4534, 4012],
  'item.length': 10},
 {'user.ids': [86],
  'user.length': 1,
  'item.ids': [121, 2340, 3527, 5293, 5732, 8300, 9, 10, 10322],
  'item.length': 9},
 {'user.ids': [87],
  'user.length': 1,
  'item.ids': [11591,
   11643,
   11804,
   11787,
   11788,
   8976,
   11515,
   11583,
   11818,
   11408],
  'item.length': 10},
 {'user.ids': [88],
  'user.length': 1,
  'item.ids': [10601, 10377, 7022, 8979, 11777, 10378, 11341],
  'item.length': 7},
 {'user.ids': [89],
  'user.length': 1,
  'item.ids': [5497, 9, 8366, 990, 408],
  'item.length': 5},
 {'user.ids': [90],
  'user.length': 1,
  'item.ids': [2305, 6442, 2505, 5094, 9, 5765, 6889],
  'item.length': 7},
 {'user.ids': [91],
  'user.length': 1,
  'item.ids': [1475, 7690, 44, 1854, 4710, 9],
  'item.length': 6},
 {'user.ids': [92],
  'user.length': 1,
  'item.ids': [51, 9, 3669, 3320, 7082, 448, 55, 4989],
  'item.length': 8},
 {'user.ids': [93],
  'user.length': 1,
  'item.ids': [6922, 9, 5378, 5412, 6699, 8741, 2967, 7751, 8218, 10258],
  'item.length': 10},
 {'user.ids': [94],
  'user.length': 1,
  'item.ids': [255, 2630, 5421, 3273, 2114, 4317, 2663, 2460, 3390, 216],
  'item.length': 10},
 {'user.ids': [95],
  'user.length': 1,
  'item.ids': [1815, 3297, 7587, 8145, 8883, 9, 5139, 630, 10952, 5192],
  'item.length': 10},
 {'user.ids': [96],
  'user.length': 1,
  'item.ids': [9978,
   4584,
   11050,
   11374,
   11714,
   11800,
   11781,
   11515,
   11236,
   11777],
  'item.length': 10},
 {'user.ids': [97],
  'user.length': 1,
  'item.ids': [9, 3213, 3276, 4668, 10078],
  'item.length': 5},
 {'user.ids': [98],
  'user.length': 1,
  'item.ids': [1636, 8552, 9395, 10, 7016],
  'item.length': 5},
 {'user.ids': [99],
  'user.length': 1,
  'item.ids': [6930, 2470, 10, 185, 209, 8711, 191, 2807],
  'item.length': 8},
 {'user.ids': [100],
  'user.length': 1,
  'item.ids': [4626, 1196, 38, 1339, 1683, 2932, 6434, 3179, 5522, 39],
  'item.length': 10},
 {'user.ids': [101],
  'user.length': 1,
  'item.ids': [8366, 10, 8216],
  'item.length': 3},
 {'user.ids': [102],
  'user.length': 1,
  'item.ids': [3558, 4336, 6802, 6840, 11269, 1521, 5182, 5194, 5522, 6997],
  'item.length': 10},
 {'user.ids': [103],
  'user.length': 1,
  'item.ids': [10498, 7594, 1490, 1732, 2524, 4691, 11, 3183, 4526, 5825],
  'item.length': 10},
 {'user.ids': [104],
  'user.length': 1,
  'item.ids': [10292, 2455, 113, 1990, 9668, 11, 1902],
  'item.length': 7},
 {'user.ids': [105],
  'user.length': 1,
  'item.ids': [5311, 9122, 4503, 8656, 10446, 5031],
  'item.length': 6},
 {'user.ids': [106],
  'user.length': 1,
  'item.ids': [1875, 11, 4227, 7993, 8249, 9962],
  'item.length': 6},
 {'user.ids': [107],
  'user.length': 1,
  'item.ids': [8215, 10561, 11, 9657],
  'item.length': 4},
 {'user.ids': [108],
  'user.length': 1,
  'item.ids': [10775,
   10808,
   10812,
   4484,
   10790,
   10164,
   11052,
   11353,
   11355,
   10830],
  'item.length': 10},
 {'user.ids': [109],
  'user.length': 1,
  'item.ids': [2270, 11, 7738],
  'item.length': 3},
 {'user.ids': [110],
  'user.length': 1,
  'item.ids': [11, 2648, 5249, 3435, 7016, 331, 4256, 5031, 7210],
  'item.length': 9},
 {'user.ids': [111],
  'user.length': 1,
  'item.ids': [4931, 5978, 6079, 6805, 6902, 11, 7642, 134, 5144, 7031],
  'item.length': 10},
 {'user.ids': [112],
  'user.length': 1,
  'item.ids': [11, 262, 2472, 7314, 8305, 8380],
  'item.length': 6},
 {'user.ids': [113],
  'user.length': 1,
  'item.ids': [2770, 2543, 10369, 10084, 11],
  'item.length': 5},
 {'user.ids': [114],
  'user.length': 1,
  'item.ids': [10807,
   11306,
   9614,
   11393,
   11422,
   11051,
   6185,
   11054,
   11704,
   6727],
  'item.length': 10},
 {'user.ids': [115],
  'user.length': 1,
  'item.ids': [5994, 6037, 5736, 11, 653, 1490, 6754],
  'item.length': 7},
 {'user.ids': [116],
  'user.length': 1,
  'item.ids': [2873, 1236, 5235],
  'item.length': 3},
 {'user.ids': [117],
  'user.length': 1,
  'item.ids': [11, 4268, 5123, 5903, 5987, 1521, 8818, 10972],
  'item.length': 8},
 {'user.ids': [118],
  'user.length': 1,
  'item.ids': [10289, 10563, 8196, 10844, 10145, 8677, 6338, 4318, 3857, 11],
  'item.length': 10},
 {'user.ids': [119],
  'user.length': 1,
  'item.ids': [649, 5165, 2710, 44, 2165, 1519, 4061, 404, 5470, 3593],
  'item.length': 10},
 {'user.ids': [120],
  'user.length': 1,
  'item.ids': [11, 861, 1943, 3289, 3333, 5619],
  'item.length': 6},
 {'user.ids': [121],
  'user.length': 1,
  'item.ids': [11, 331, 1370, 1490, 2276, 2319, 8807, 9129],
  'item.length': 8},
 {'user.ids': [122],
  'user.length': 1,
  'item.ids': [11, 6434, 6435, 7916, 9398, 3704, 11301],
  'item.length': 7},
 {'user.ids': [123],
  'user.length': 1,
  'item.ids': [11, 2052, 2872, 9551, 11452],
  'item.length': 5},
 {'user.ids': [124],
  'user.length': 1,
  'item.ids': [5713, 11, 135, 2943, 9127],
  'item.length': 5},
 {'user.ids': [125],
  'user.length': 1,
  'item.ids': [11, 5945, 2571, 2906, 4085, 6079],
  'item.length': 6},
 {'user.ids': [126],
  'user.length': 1,
  'item.ids': [1838, 4526, 5194, 5327, 11, 7734, 552, 2178, 7935, 8643],
  'item.length': 10},
 {'user.ids': [127],
  'user.length': 1,
  'item.ids': [8816, 1207, 4735, 11, 1539],
  'item.length': 5},
 {'user.ids': [128],
  'user.length': 1,
  'item.ids': [11, 6037],
  'item.length': 2},
 {'user.ids': [129],
  'user.length': 1,
  'item.ids': [5231, 5755, 1053, 1548, 5994, 9166, 9770, 1562, 1952, 10016],
  'item.length': 10},
 {'user.ids': [130],
  'user.length': 1,
  'item.ids': [7058, 7170, 7724, 9100],
  'item.length': 4},
 {'user.ids': [131],
  'user.length': 1,
  'item.ids': [5133, 9280, 11, 3994, 8142, 9530, 10124],
  'item.length': 7},
 {'user.ids': [132],
  'user.length': 1,
  'item.ids': [4450, 4753, 4955, 5180, 5787, 5929, 7830, 7831, 9944, 9953],
  'item.length': 10},
 {'user.ids': [133],
  'user.length': 1,
  'item.ids': [1190, 2199, 3006],
  'item.length': 3},
 {'user.ids': [134],
  'user.length': 1,
  'item.ids': [6728, 3837, 7827, 11],
  'item.length': 4},
 {'user.ids': [135],
  'user.length': 1,
  'item.ids': [10533, 11, 7597],
  'item.length': 3},
 {'user.ids': [136],
  'user.length': 1,
  'item.ids': [11,
   10373,
   11229,
   11320,
   11703,
   11706,
   11714,
   11704,
   11683,
   11787],
  'item.length': 10},
 {'user.ids': [137],
  'user.length': 1,
  'item.ids': [2386, 588, 979, 11, 269, 298, 1819, 9477, 3114, 6832],
  'item.length': 10},
 {'user.ids': [138],
  'user.length': 1,
  'item.ids': [11, 7295, 1055, 2843, 3951, 4200],
  'item.length': 6},
 {'user.ids': [139],
  'user.length': 1,
  'item.ids': [7087, 59, 4626, 4968, 2319, 7091, 11, 4332],
  'item.length': 8},
 {'user.ids': [140],
  'user.length': 1,
  'item.ids': [6079, 4075, 7087, 11, 3435],
  'item.length': 5},
 {'user.ids': [141],
  'user.length': 1,
  'item.ids': [8044, 3974],
  'item.length': 2},
 {'user.ids': [142],
  'user.length': 1,
  'item.ids': [1213, 3297, 4446, 6312, 331, 98, 2165, 2768, 159, 664],
  'item.length': 10},
 {'user.ids': [143],
  'user.length': 1,
  'item.ids': [11, 5177, 5412, 5414, 119, 6278, 404, 405, 9530],
  'item.length': 9},
 {'user.ids': [144],
  'user.length': 1,
  'item.ids': [8124, 11, 4520, 10856, 9781, 8954],
  'item.length': 6},
 {'user.ids': [145],
  'user.length': 1,
  'item.ids': [816, 2695, 551, 5825, 11, 490, 2915, 5034],
  'item.length': 8},
 {'user.ids': [146],
  'user.length': 1,
  'item.ids': [5522, 6079, 9488, 11, 1423, 5825, 8932, 9122, 9530, 9556],
  'item.length': 10},
 {'user.ids': [147],
  'user.length': 1,
  'item.ids': [2785, 9100, 9968, 11, 3617, 7621, 10470],
  'item.length': 7},
 {'user.ids': [148],
  'user.length': 1,
  'item.ids': [11, 202, 437, 688, 1976, 2635],
  'item.length': 6},
 {'user.ids': [149],
  'user.length': 1,
  'item.ids': [5528, 3719, 6325, 2861, 11, 1789, 6334, 9123],
  'item.length': 8},
 {'user.ids': [150],
  'user.length': 1,
  'item.ids': [11, 6562, 8938, 7774, 1675],
  'item.length': 5},
 {'user.ids': [151],
  'user.length': 1,
  'item.ids': [6572, 4117, 1357, 1899, 5200, 4465, 67, 1739, 4336, 5522],
  'item.length': 10},
 {'user.ids': [152],
  'user.length': 1,
  'item.ids': [196, 11, 406, 3075, 97, 98, 2684, 4217, 6311, 8084],
  'item.length': 10},
 {'user.ids': [153],
  'user.length': 1,
  'item.ids': [3618, 5182, 5402, 7437, 6937, 12, 2446, 5712],
  'item.length': 8},
 {'user.ids': [154],
  'user.length': 1,
  'item.ids': [3597, 2010, 2274, 7815, 12],
  'item.length': 5},
 {'user.ids': [155],
  'user.length': 1,
  'item.ids': [2983, 4018, 7070, 9495, 2158, 20, 1162, 12, 4465, 8243],
  'item.length': 10},
 {'user.ids': [156],
  'user.length': 1,
  'item.ids': [12, 10479, 11248, 2077, 2339, 5160, 11661, 2741, 4116, 3071],
  'item.length': 10},
 {'user.ids': [157],
  'user.length': 1,
  'item.ids': [6851, 7344, 4037, 164, 2865, 3018, 1181, 1406, 1169, 3917],
  'item.length': 10},
 {'user.ids': [158],
  'user.length': 1,
  'item.ids': [6400, 13, 3734, 5053, 6984, 7241, 869, 9542],
  'item.length': 8},
 {'user.ids': [159],
  'user.length': 1,
  'item.ids': [13, 4882, 5079, 10552, 8243, 10632],
  'item.length': 6},
 {'user.ids': [160],
  'user.length': 1,
  'item.ids': [13, 125, 5915, 6802, 10138, 10513],
  'item.length': 6},
 {'user.ids': [161],
  'user.length': 1,
  'item.ids': [140, 6245, 9405, 9613, 9936, 7673, 6552, 6776, 8455, 4905],
  'item.length': 10},
 {'user.ids': [163],
  'user.length': 1,
  'item.ids': [4054, 3604, 1365, 1989, 9029, 9935, 7804, 8159, 9778, 13],
  'item.length': 10},
 {'user.ids': [164],
  'user.length': 1,
  'item.ids': [6285, 3142, 9524, 6545, 159, 13, 4060, 6133, 9162],
  'item.length': 9},
 {'user.ids': [165],
  'user.length': 1,
  'item.ids': [3053, 13, 2054, 3792, 11723],
  'item.length': 5},
 {'user.ids': [166],
  'user.length': 1,
  'item.ids': [4208, 4290, 5051, 5842, 6051, 6843, 7803, 9051, 10957, 11298],
  'item.length': 10},
 {'user.ids': [167], 'user.length': 1, 'item.ids': [13, 84], 'item.length': 2},
 {'user.ids': [168],
  'user.length': 1,
  'item.ids': [5197, 1280, 2326, 3978, 6991, 10960, 4744, 8761, 3582, 1842],
  'item.length': 10},
 {'user.ids': [169],
  'user.length': 1,
  'item.ids': [7265, 1321, 1771, 13, 2754, 4477, 2241, 5707, 9109, 10312],
  'item.length': 10},
 {'user.ids': [170],
  'user.length': 1,
  'item.ids': [747, 185, 999, 7876, 2272, 5488, 5782, 13, 2698],
  'item.length': 9},
 {'user.ids': [172],
  'user.length': 1,
  'item.ids': [8365, 8393, 13, 8901, 7653, 6727, 3379, 11183, 4526],

In [6]:
df = pd.read_csv(data_path)

In [10]:
user_items = df.groupby("user_id")["item_id"].apply(list).to_dict()
index = []
max_sequence_length = 10
for user_idx, item_ids in sorted(list(user_items.items()), key=lambda x: x[0]):
    index.append(
        {
            "user.ids": [user_idx],
            "user.length": 1,
            "item.ids": item_ids[-max_sequence_length :],
            "item.length": len(item_ids[-max_sequence_length :]),
        }
    )

In [ ]:
for user_idx, item_ids in sorted(list(user_items.items()), key=lambda x: x[0]):

{1: [6846, 7873, 4585, 1],
 3: [1, 6050, 7977, 5252, 4211, 243],
 4: [5522, 439, 5161, 11140, 1],
 5: [1, 10470, 10064, 9403, 10362, 4758, 6500, 11444],
 6: [6906,
  7241,
  5662,
  1,
  411,
  5133,
  6404,
  8816,
  4595,
  9917,
  6046,
  9597,
  8819,
  6431,
  9562,
  5664],
 7: [8499, 8778, 1796, 5987, 6059, 10038],
 8: [8997, 4554, 6928, 1],
 9: [373,
  4488,
  6865,
  5161,
  5920,
  7454,
  3974,
  1203,
  6236,
  11095,
  9383,
  2722,
  3697,
  5488,
  11243,
  11288,
  10357,
  3894,
  4352,
  9557,
  3362],
 10: [1928, 2171, 2228, 2],
 11: [1190],
 12: [4211, 3275, 6325, 9046, 7591, 2, 8643],
 13: [6322, 5528, 7437, 10874],
 14: [2, 138, 2937, 5128, 8517, 1307, 8327],
 15: [11518, 8579, 11256, 2, 1305, 2047],
 16: [6276],
 17: [6534, 8958, 2, 2421],
 18: [11111],
 19: [5244, 8815, 2],
 20: [6067,
  5404,
  7448,
  7462,
  7798,
  771,
  1094,
  3228,
  4258,
  1697,
  2746,
  2949,
  5318,
  7172,
  1053,
  1962,
  2400,
  2506,
  2835,
  3890,
  8104,
  3,
  6778,
  2998,
  575,
  6906,
  390,
  9165,
  3208,
  6231,
  8966,
  9272,
  6161,
  5040,
  7840],
 21: [2837, 7830, 3, 816, 1426, 3538],
 22: [3, 6539, 6540, 6158, 5379, 9600, 298, 10781, 11070, 8543, 1354, 71],
 23: [1064, 394, 891, 1950, 1971, 2060, 2544, 2992, 4064, 5259, 5318],
 24: [6304, 7363, 7678, 3, 7907, 8789, 8661, 9673],
 26: [6649, 1596, 2544, 3537, 5688, 4, 1977, 502],
 27: [7815,
  8839,
  9504,
  4,
  2545,
  4424,
  5975,
  7196,
  7336,
  7745,
  7759,
  7985,
  8373,
  8600,
  9562,
  10034,
  10338,
  2440,
  7164,
  7266,
  9403,
  11131,
  3539,
  4544,
  10933,
  448,
  11170,
  827,
  4628,
  5493,
  6498,
  8590,
  2622,
  4465,
  5903,
  5972,
  5997,
  6096,
  6309,
  6622,
  8124,
  8824,
  9120,
  9759,
  9992,
  10450,
  8440,
  8742,
  6660,
  6937,
  8136,
  8586,
  11492,
  10750,
  11446,
  5254,
  10163,
  8127,
  8150,
  8816,
  9369,
  9484,
  10132,
  10979,
  3535,
  7532,
  8969,
  10218,
  10802,
  10179,
  6078,
  6599,
  9781,
  10632,
  11575,
  10472,
  7849,
  9839,
  10594,
  11004],
 28: [1076, 1423, 1477, 6285, 1015, 4588],
 29: [8802, 7469, 10822, 5325, 8087, 3903, 4],
 30: [921, 730, 6192, 4460, 1854, 1712, 3756, 414],
 31: [5, 3099, 1251, 759],
 32: [419,
  1545,
  2452,
  2506,
  1433,
  3098,
  1423,
  2314,
  1053,
  409,
  3836,
  3101,
  3100,
  1758,
  4403,
  5882,
  6433,
  5448,
  6435,
  9588,
  9582,
  9583,
  9589,
  10566,
  10568,
  10561,
  10559,
  10562,
  8561,
  10560,
  8558,
  10711,
  10810,
  10812,
  10897,
  1135,
  10669,
  10689,
  1166,
  10896,
  11734,
  11732,
  7114,
  11772],
 33: [1189, 5, 3373, 1755, 2315, 2791, 3799, 5113, 388, 3314, 9672],
 34: [5, 1066, 1086, 791, 2413, 2452, 801, 1974, 1433, 1363, 2171, 55],
 35: [268,
  5117,
  6670,
  7419,
  7436,
  11474,
  5,
  265,
  3272,
  5416,
  6037,
  10089,
  10136],
 36: [5583,
  1553,
  7092,
  6,
  362,
  3992,
  4667,
  7037,
  9224,
  5935,
  6693,
  6811,
  10323,
  6169,
  6613],
 37: [6, 999, 1247, 1452, 5273, 6046],
 39: [464, 4993],
 40: [3275, 5196, 5963, 7033, 8249, 8816, 9081, 85, 5194, 6, 3579, 9603, 9716],
 41: [4866, 6352, 8042, 6],
 42: [6, 7155, 3498, 2329, 3540, 6547, 921, 4367, 6589],
 43: [1636, 2319, 2758, 6501, 628, 1138, 1249, 312, 3788],
 44: [426,
  2785,
  4800,
  1339,
  3056,
  6,
  39,
  41,
  191,
  231,
  261,
  1121,
  1254,
  1813,
  2360,
  2606,
  3011,
  4675,
  5308,
  6192,
  6260,
  6283,
  6581,
  7057,
  7281,
  7590,
  7633,
  8096,
  9208,
  2915,
  4230,
  2262,
  2310,
  4108,
  5053,
  5903,
  8249,
  8478,
  9329],
 45: [4899, 2358, 6, 1245, 1609],
 46: [6, 1024, 840, 8421],
 47: [2854, 6, 370, 447, 2426, 2830, 2158],
 48: [3068, 318, 493, 6, 3647],
 49: [4411, 2076, 2420, 6, 4966, 3068, 6584, 7727, 2183, 772],
 50: [5976, 7595, 2599, 5193, 9947, 7791, 6, 6266, 9714, 9061],
 51: [1318, 4207, 4955, 9215, 5751, 577, 7683],
 52: [4691, 6, 9471, 388, 390, 6683],
 53: [6, 5314, 5749, 5307, 5382],
 54: [4481,
  317,
  777,
  1094,
  2599,
  3747,
  5663,
  5926,
  6982,
  7499,
  6,
  494,
  2764,
  6573,
  6833,
  8772],
 55: [6, 196, 444, 689, 727, 4768, 8048],
 57: [6, 1307, 1732, 5803, 6552, 9163],
 58: [4449, 8252, 2148, 5488, 4868, 7, 5878, 2045],
 59: [7, 7130, 8518, 8615, 8648, 8386],
 60: [931, 2335, 7, 1567, 2868, 3216, 8166],
 61: [7, 4956],
 62: [5908, 7, 1414, 220],
 63: [1450,
  4271,
  4059,
  4040,
  4041,
  4676,
  6115,
  8555,
  9589,
  9468,
  9595,
  10566,
  10700,
  10698,
  10897,
  10164,
  10691,
  10896,
  10373,
  10374],
 64: [7, 2710, 5294, 4205, 3768, 2776, 6613, 2778],
 65: [4050, 3916, 4675, 8351, 8384, 4647],
 66: [5385, 3650, 7],
 67: [3339, 9782, 5410, 9476, 7],
 68: [4201, 7, 1818, 9816],
 69: [7, 8227, 8, 2532],
 70: [4025,
  3134,
  7089,
  5609,
  9592,
  9585,
  3716,
  4858,
  5607,
  5608,
  2616,
  8561,
  10389,
  8562,
  9087,
  10759,
  9288,
  10689,
  10984,
  8387,
  10896,
  3625,
  5931,
  3311,
  10378],
 71: [7, 6727, 917, 8267],
 73: [7670, 7],
 74: [11379, 51, 2028, 2648, 2789, 3060, 3298, 4341, 6192],
 76: [7, 2035, 2253, 3046],
 77: [7314, 7, 6866, 6844],
 78: [2261, 1089],
 79: [7,
  8658,
  9005,
  8727,
  9550,
  3712,
  11647,
  11760,
  11777,
  11804,
  4016,
  11773],
 80: [2606,
  8416,
  7,
  2304,
  3885,
  536,
  3811,
  4735,
  5749,
  8300,
  9612,
  5987,
  9144],
 81: [616,
  2704,
  7699,
  3356,
  5030,
  5172,
  9214,
  2345,
  6767,
  5200,
  2429,
  4361,
  6770,
  6830,
  1282,
  5718,
  159,
  8678,
  21,
  6274,
  149],
 82: [8715, 8, 7138, 8969, 7532, 8633, 8824, 2987, 9712, 6880],
 83: [2757,
  7917,
  9003,
  3574,
  8,
  611,
  2493,
  3337,
  3567,
  5465,
  5473,
  5698,
  7594,
  8631],
 84: [4676, 4653, 8730, 9585, 5369, 2346, 8, 10302, 3856, 10377],
 85: [5611, 2393, 6589, 2605, 9, 3813, 4085, 6269, 11194, 4534],
 86: [121, 2340, 3527, 5293, 5732, 8300, 9, 10],
 87: [1229,
  4201,
  8730,
  591,
  9589,
  9457,
  8686,
  10300,
  9,
  5497,
  8560,
  10559,
  10560,
  10561,
  10564,
  10506,
  10694,
  917,
  8676,
  10528,
  8807,
  10774,
  10775,
  10776,
  8562,
  10387,
  10538,
  10810,
  10812,
  10813,
  10690,
  10699,
  10705,
  10710,
  10669,
  10912,
  5091,
  10373,
  10374,
  11396,
  5500,
  6966,
  9906,
  10376,
  11348,
  11179,
  7218,
  11703,
  11683,
  11591,
  11643,
  11804,
  11787,
  11788,
  8976,
  11515,
  11583,
  11818],
 88: [10601, 10377, 7022, 8979, 11777, 10378],
 89: [5497, 9, 8366, 990],
 90: [2305, 6442, 2505, 5094, 9, 5765],
 91: [1475, 7690, 44, 1854, 4710],
 92: [51, 9, 3669, 3320, 7082, 448, 55],
 93: [5413, 6922, 9, 5378, 5412, 6699, 8741, 2967, 7751, 8218],
 94: [2797,
  9,
  268,
  3230,
  8835,
  2133,
  5207,
  3829,
  255,
  2630,
  5421,
  3273,
  2114,
  4317,
  2663,
  2460,
  3390],
 95: [5219,
  6918,
  2481,
  2681,
  2932,
  7370,
  1750,
  2236,
  2238,
  6817,
  7356,
  43,
  44,
  262,
  4403,
  4917,
  2745,
  1815,
  3297,
  7587,
  8145,
  8883,
  9,
  5139,
  630,
  10952],
 96: [3561,
  1093,
  9,
  215,
  216,
  73,
  74,
  77,
  3693,
  681,
  1962,
  6823,
  5968,
  3334,
  191,
  688,
  7840,
  487,
  433,
  7370,
  9457,
  10080,
  9328,
  5910,
  2921,
  8556,
  10561,
  10565,
  10670,
  7847,
  10562,
  10566,
  10702,
  10701,
  10538,
  10570,
  10560,
  10572,
  3714,
  10774,
  10573,
  1135,
  7457,
  10897,
  10559,
  10669,
  10689,
  6532,
  10896,
  10691,
  9951,
  5091,
  5092,
  10373,
  5090,
  10374,
  8387,
  9978,
  4584,
  11050,
  11374,
  11714,
  11800,
  11781,
  11515,
  11236],
 97: [9, 3213, 3276, 4668],
 98: [1636, 8552, 9395, 10],
 99: [6930, 2470, 10, 185, 209, 8711, 191],
 100: [1207, 4626, 1196, 38, 1339, 1683, 2932, 6434, 3179, 5522],
 101: [8366, 10],
 102: [6841,
  11,
  151,
  1490,
  3788,
  5825,
  8800,
  3097,
  3558,
  4336,
  6802,
  6840,
  11269,
  1521,
  5182,
  5194,
  5522],
 103: [3841, 10498, 7594, 1490, 1732, 2524, 4691, 11, 3183, 4526],
 104: [10292, 2455, 113, 1990, 9668, 11],
 105: [5311, 9122, 4503, 8656, 10446],
 106: [1875, 11, 4227, 7993, 8249],
 107: [8215, 10561, 11],
 108: [3556,
  3637,
  3638,
  4153,
  2330,
  4152,
  2068,
  5968,
  6116,
  6433,
  7296,
  9397,
  9591,
  9457,
  9459,
  9587,
  10402,
  2618,
  9250,
  10562,
  10693,
  10694,
  10559,
  10560,
  10707,
  3702,
  10774,
  10573,
  10709,
  10570,
  1135,
  10704,
  10773,
  10775,
  10808,
  10812,
  4484,
  10790,
  10164,
  11052,
  11353,
  11355],
 109: [2270, 11],
 110: [11, 2648, 5249, 3435, 7016, 331, 4256, 5031],
 111: [127,
  1490,
  2321,
  1492,
  2246,
  2622,
  3467,
  3603,
  3762,
  4139,
  4229,
  4931,
  5978,
  6079,
  6805,
  6902,
  11,
  7642,
  134,
  5144],
 112: [11, 262, 2472, 7314, 8305],
 113: [2770, 2543, 10369, 10084],
 114: [1213,
  11,
  1288,
  2335,
  2070,
  3751,
  7079,
  5533,
  104,
  5246,
  10107,
  5783,
  9584,
  9253,
  7441,
  9591,
  9595,
  10807,
  11306,
  9614,
  11393,
  11422,
  11051,
  6185,
  11054,
  11704],
 115: [5994, 6037, 5736, 11, 653, 1490],
 116: [2873, 1236],
 117: [11, 4268, 5123, 5903, 5987, 1521, 8818],
 118: [5024,
  8169,
  4580,
  4581,
  2519,
  4013,
  5948,
  10383,
  10292,
  1674,
  10809,
  10810,
  5049,
  10388,
  10814,
  10289,
  10563,
  8196,
  10844,
  10145,
  8677,
  6338,
  4318,
  3857],
 119: [3121,
  4682,
  6521,
  2272,
  4181,
  3343,
  7796,
  7797,
  1586,
  2126,
  7820,
  4012,
  5653,
  6553,
  2496,
  11,
  959,
  5552,
  447,
  7281,
  3260,
  727,
  904,
  3254,
  3955,
  649,
  5165,
  2710,
  44,
  2165,
  1519,
  4061,
  404,
  5470],
 120: [11, 861, 1943, 3289, 3333],
 121: [11, 331, 1370, 1490, 2276, 2319, 8807],
 122: [11, 6434, 6435, 7916, 9398, 3704],
 123: [11, 2052, 2872, 9551],
 124: [5713, 11, 135, 2943],
 125: [11, 5945, 2571, 2906, 4085],
 126: [1838, 4526, 5194, 5327, 11, 7734, 552, 2178, 7935],
 127: [8816, 1207, 4735, 11],
 128: [11],
 129: [11, 5231, 5755, 1053, 1548, 5994, 9166, 9770, 1562, 1952],
 130: [7058, 7170, 7724],
 131: [5133, 9280, 11, 3994, 8142, 9530],
 132: [11,
  2063,
  2922,
  5108,
  8335,
  233,
  5289,
  8635,
  553,
  1862,
  3338,
  4450,
  4753,
  4955,
  5180,
  5787,
  5929,
  7830,
  7831,
  9944],
 133: [1190, 2199],
 134: [6728, 3837, 7827],
 135: [10533, 11],
 136: [3348,
  1586,
  3843,
  4271,
  2363,
  3952,
  535,
  3064,
  488,
  4164,
  143,
  76,
  2999,
  855,
  4651,
  4488,
  2171,
  1153,
  3300,
  6013,
  3841,
  7072,
  1776,
  7101,
  5298,
  7901,
  7876,
  7370,
  9591,
  7610,
  5946,
  10080,
  9584,
  9589,
  8061,
  9587,
  3922,
  4042,
  9590,
  8560,
  8561,
  8562,
  10568,
  10565,
  4567,
  10528,
  10566,
  917,
  8556,
  10704,
  8676,
  10707,
  10774,
  10560,
  10561,
  10164,
  5500,
  10912,
  6966,
  9906,
  11,
  10373,
  11229,
  11320,
  11703,
  11706,
  11714,
  11704,
  11683],
 137: [1179,
  1994,
  1298,
  5729,
  6193,
  2184,
  340,
  2386,
  588,
  979,
  11,
  269,
  298,
  1819,
  9477,
  3114],
 138: [11, 7295, 1055, 2843, 3951],
 139: [7087, 59, 4626, 4968, 2319, 7091, 11],
 140: [6079, 4075, 7087, 11],
 141: [8044],
 142: [11, 9029, 1213, 3297, 4446, 6312, 331, 98, 2165, 2768, 159],
 143: [11, 5177, 5412, 5414, 119, 6278, 404, 405],
 144: [8124, 11, 4520, 10856, 9781],
 145: [816, 2695, 551, 5825, 11, 490, 2915],
 146: [8569,
  3369,
  4231,
  5194,
  5250,
  5522,
  6079,
  9488,
  11,
  1423,
  5825,
  8932,
  9122,
  9530],
 147: [2785, 9100, 9968, 11, 3617, 7621],
 148: [11, 202, 437, 688, 1976],
 149: [5528, 3719, 6325, 2861, 11, 1789, 6334],
 150: [11, 6562, 8938, 7774],
 151: [5143,
  5429,
  5944,
  547,
  6855,
  11,
  286,
  195,
  1633,
  5831,
  6061,
  5432,
  6572,
  4117,
  1357,
  1899,
  5200,
  4465,
  67,
  1739,
  4336],
 152: [196, 11, 406, 3075, 97, 98, 2684, 4217, 6311],
 153: [3618, 5182, 5402, 7437, 6937, 12, 2446],
 154: [3597, 2010, 2274, 7815],
 155: [2983, 4018, 7070, 9495, 2158, 20, 1162, 12, 4465],
 156: [2913,
  6570,
  5613,
  9166,
  6164,
  5743,
  12,
  10479,
  11248,
  2077,
  2339,
  5160,
  11661,
  2741,
  4116],
 157: [113,
  12,
  112,
  3064,
  10338,
  2807,
  3635,
  5031,
  5344,
  6727,
  6851,
  7344,
  4037,
  164,
  2865,
  3018,
  1181,
  1406,
  1169],
 158: [6400, 13, 3734, 5053, 6984, 7241, 869],
 159: [13, 4882, 5079, 10552, 8243],
 160: [13, 125, 5915, 6802, 10138],
 161: [13, 140, 6245, 9405, 9613, 9936, 7673, 6552, 6776, 8455],
 163: [4054, 3604, 1365, 1989, 9029, 9935, 7804, 8159, 9778],
 164: [6285, 3142, 9524, 6545, 159, 13, 4060, 6133],
 165: [3053, 13, 2054, 3792],
 166: [8836, 13, 2345, 4208, 4290, 5051, 5842, 6051, 6843, 7803, 9051, 10957],
 167: [13],
 168: [124,
  3948,
  3949,
  4850,
  4852,
  4872,
  5376,
  5908,
  2821,
  7057,
  13,
  6030,
  1407,
  7350,
  900,
  4614,
  6412,
  2244,
  6930,
  1413,
  1652,
  9501,
  5197,
  1280,
  2326,
  3978,
  6991,
  10960,
  4744,
  8761,
  3582],
 169: [5040,
  274,
  3562,
  4018,
  267,
  2254,
  3276,
  4236,
  2092,
  1772,
  1319,
  1508,
  3591,
  5192,
  8548,
  1646,
  2391,
  1521,
  5280,
  4495,
  89,
  2972,
  3313,
  3614,
  6770,
  4362,
  7127,
  40,
  912,
  7265,
  1321,
  1771,
  13,
  2754,
  4477,
  2241,
  5707,
  9109],
 170: [747, 185, 999, 7876, 2272, 5488, 5782, 13],
 172: [8365, 8393, 13, 8901, 7653, 6727, 3379, 11183],
 174: [9366, 9857, 10248],
 175: [13, 1472, 3181, 3983, 5031, 10033, 8759],
 176: [4950, 13, 5522, 6875, 8646, 9306, 7366],
 177: [1976, 2248, 15, 4168, 13],
 178: [4487, 5133, 6080, 7854, 8033, 8797, 13, 2326, 5200, 10561, 10564],
 179: [1121,
  512,
  844,
  110,
  181,
  1748,
  664,
  3725,
  2300,
  1945,
  3802,
  2664,
  3473,
  2420,
  256,
  982,
  3348,
  3768,
  641,
  776,
  2132,
  370,
  195,
  4052,
  4041,
  4149,
  882,
  4631,
  127,
  4653,
  4652,
  6955,
  4917,
  4636,
  7079,
  1586,
  1190,
  387,
  6355,
  3318,
  4144,
  4733,
  4741,
  4794,
  7117,
  7121,
  7224,
  8448,
  4336,
  5716,
  1623,
  2648,
  9595,
  9588,
  2367,
  179,
  5596,
  4089,
  2247,
  9885,
  8462,
  10169,
  5033,
  3712,
  10291,
  727,
  5783,
  10566,
  10790,
  10569,
  10775,
  1135,
  10567,
  10896,
  2662,
  10709,
  10710,
  8190,
  2702,
  2705,
  3235,
  3240,
  5492,
  9129,
  147,
  3514,
  7804,
  10289,
  10881,
  10897,
  4595,
  5522,
  9123,
  9936,
  7812,
  2246,
  7829,
  6725,
  1313,
  8387,
  3994,
  5432,
  6837,
  4566,
  9183,
  10946,
  5194,
  10839,
  10691,
  6875,
  9055,
  5090,
  6224,
  6641,
  10945,
  4334,
  5521,
  5712,
  8050,
  9604,
  10895,
  10898,
  10899,
  11320,
  11374,
  10546,
  11230,
  8436,
  11615,
  917,
  7642,
  7928,
  8269,
  9808,
  9962,
  10549,
  11380,
  8139,
  10479,
  649,
  75,
  2503,
  3445,
  4442,
  6388,
  7254,
  7874,
  9297,
  5375,
  6003,
  111,
  4087,
  5031,
  13,
  2419,
  10959,
  4335,
  4793,
  11217,
  10378,
  11811,
  3996,
  9598,
  11771],
 180: [13, 5131, 5429, 6838, 6843, 8824],
 181: [658, 3339, 8537, 1731, 2935, 13],
 182: [1254, 1675],
 183: [6281, 8824, 11361, 13, 7122, 9432, 10035, 10230],
 185: [7001, 3963, 5613, 13, 3252, 3248, 7874, 390],
 186: [8267,
  10294,
  10546,
  13,
  1370,
  2109,
  2353,
  4079,
  4744,
  5051,
  6433,
  6967,
  7812,
  10685,
  10704,
  10821],
 187: [1678, 5708, 2191, 9323, 5301],
 188: [804, 2728, 6227],
 189: [13, 448, 3982, 5034],
 190: [5710, 1911, 4343, 13, 2319],
 191: [13, 656, 3130, 3131, 10724],
 192: [13, 3994, 5430, 5736, 8452, 2584, 2698, 4355],
 194: [771],
 195: [7110, 82, 7653, 8569],
 196: [13,
  3467,
  4378,
  4792,
  6104,
  6231,
  6549,
  6805,
  8401,
  8823,
  9122,
  9528,
  2147,
  4089,
  4457,
  4904,
  6973,
  7849],
 197: [2701, 3630, 4227, 5356, 5358],
 198: [4921,
  6317,
  6318,
  532,
  56,
  5274,
  5826,
  1346,
  3692,
  36,
  145,
  3639,
  5728,
  204,
  13,
  6108,
  3995,
  859,
  2110,
  10561,
  3701,
  2666,
  11426,
  10752,
  10753,
  8727,
  10373,
  10374,
  10958,
  9604,
  9165,
  3603,
  3978,
  11220,
  11216,
  11769,
  11777],
 199: [3924, 2018],
 200: [4795,
  7646,
  8479,
  8512,
  1670,
  3551,
  7648,
  1521,
  1789,
  4989,
  5522,
  7700,
  7701,
  9734,
  9744,
  2438,
  5194,
  5588,
  8243,
  8498,
  11175,
  4735,
  6491,
  7345,
  7561,
  8651,
  2101,
  4140,
  5196,
  6916,
  7424,
  8502,
  4209,
  4737,
  8476,
  8481,
  9639,
  10717,
  10971,
  13,
  64,
  1254,
  5716],
 201: [13, 2345, 4133, 4696, 6004],
 202: [8375,
  3995,
  4794,
  6108,
  7117,
  7661,
  9800,
  7122,
  1350,
  2326,
  3234,
  8607,
  13,
  6805,
  8332,
  3238,
  5053,
  2693,
  4737,
  4797,
  2909,
  3592,
  9365,
  6397,
  7805,
  10020,
  3275,
  8643,
  127,
  6331,
  3836,
  8252,
  8254,
  10354],
 203: [267,
  698,
  13,
  8124,
  8636,
  545,
  627,
  1945,
  6091,
  7146,
  7942,
  8241,
  8528,
  8985,
  9305,
  9702,
  9794],
 204: [356, 13, 6725],
 205: [6311,
  7502,
  4648,
  4526,
  4094,
  9530,
  13,
  2179,
  2908,
  4144,
  4426,
  6843,
  9054,
  9774,
  4127,
  3734,
  6840,
  7121,
  258,
  10771],
 206: [840, 7075, 13, 3049, 3157, 408, 167, 1684, 6954, 1225, 140, 7057, 1924],
 207: [13, 11360, 2149, 5492],
 208: [2188,
  5602,
  14,
  5369,
  6278,
  2771,
  1411,
  2560,
  2566,
  9162,
  2573,
  53,
  1134,
  3797,
  3805,
  3806,
  7766,
  190,
  2189,
  3667,
  405,
  4643,
  553,
  718,
  2171,
  5399,
  5962,
  7373,
  10095,
  7178,
  5918,
  2915,
  561,
  4646],
 209: [3390, 14, 2648, 2987, 5133, 5522, 6805],
 210: [14, 2319, 2993, 3018],
 211: [14, 187, 2160, 2210, 3852, 7571, 8167],
 212: [8146, 14, 7832, 2827],
 213: [10609, 2319, 4526, 1335, 14, 8999, 7059, 11544, 4670],
 214: [1005, 1146],
 215: [14, 522, 4164, 1822],
 216: [6021, 452, 14],
 218: [7451, 2378, 7475, 9219],
 219: [8970, 6413, 14, 1408, 1511, 6545, 7011, 10512],
 220: [1335, 4091, 5050, 5813, 9390],
 221: [3208, 6599, 7008, 4022, 14, 6063, 6796, 7121, 7821, 7460],
 222: [14, 2071, 2411, 2770, 6311],
 223: [14, 575, 6727],
 224: [9214, 14, 167, 187, 1728, 5957, 7472],
 225: [104,
  101,
  102,
  23,
  116,
  317,
  327,
  158,
  256,
  740,
  129,
  494,
  262,
  493,
  99,
  295,
  728,
  110,
  161,
  96,
  115,
  202,
  981,
  160,
  208,
  2097,
  3645,
  895,
  4863,
  408,
  407,
  3803,
  1129,
  426,
  734,
  1958,
  980,
  1611,
  144,
  1310,
  1078,
  1221,
  1401,
  419,
  418,
  416,
  2627,
  2599,
  733,
  3939,
  365,
  3102,
  2604,
  3241,
  3848,
  1245,
  3065,
  6138,
  3751,
  1410,
  4921,
  7792,
  6188,
  226,
  4438,
  6136,
  7231,
  1189,
  3473,
  4140,
  5600,
  3932,
  7247,
  5055,
  4505,
  5513,
  1896,
  103,
  9585,
  8727,
  8728,
  8730,
  8379,
  5973,
  10318,
  5088,
  8668,
  10690,
  6555,
  6139,
  4288,
  4286,
  4287,
  10704,
  7847,
  2618,
  5165,
  11085,
  1769,
  11352,
  10376,
  10388,
  9151,
  14,
  187,
  11334,
  8976,
  8977],
 226: [14, 3368, 3739, 5029, 5505],
 227: [269, 422, 1934, 2731, 14, 185, 1165, 2863, 7065, 4204],
 228: [1788, 2823, 14, 3428],
 229: [5528, 11613, 4123, 7124],
 230: [34,
  344,
  589,
  19,
  15,
  4082,
  4101,
  6972,
  8146,
  1490,
  6398,
  10140,
  1336,
  1508],
 232: [6975, 3635, 7072, 15],
 233: [3554, 7272, 5088, 7486, 7847],
 234: [5605, 5145, 6050],
 235: [6954, 1069, 4634, 654, 2756, 7905, 205, 4521, 9128, 15, 10160, 6980],
 236: [15, 11152, 7849],
 238: [15],
 239: [4197,
  1162,
  6548,
  15,
  5672,
  7295,
  4049,
  7294,
  8559,
  5431,
  8555,
  4465,
  6078,
  8949,
  4379,
  7817,
  7804,
  7064,
  4882,
  9588,
  9587,
  9457,
  2236,
  6733,
  5253,
  10301,
  8146,
  5528,
  7179,
  10528,
  6974,
  10162,
  8558,
  7847,
  917,
  10562,
  10700,
  10559,
  10565,
  8676,
  10564,
  10670,
  10707,
  10710,
  10775,
  10709,
  10773,
  10699,
  10774,
  10812,
  10816,
  5825,
  11212,
  9420,
  11010,
  10669,
  10689,
  10691,
  10896,
  9679,
  7805,
  5500,
  10912,
  6966,
  8428,
  8427,
  7586,
  7135,
  8425,
  8426,
  5225,
  1216,
  1315,
  7316,
  7218,
  2244,
  11282,
  11397,
  11398,
  11230,
  11320,
  6602,
  11052,
  11057,
  8423,
  7510,
  187,
  9703,
  11715,
  11770],
 240: [1684,
  4834,
  6636,
  7491,
  3266,
  2680,
  1980,
  15,
  8713,
  7187,
  2937,
  5825,
  8447,
  9165],
 241: [15, 2223, 4398, 3371],